INSERT INTO PASSPORT(PASSPORT_ID, PASSPORT_NUMBER)
VALUES('301', 'E12345');


INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME, PASSPORT_ID)
VALUES('123', 'Rahul','301' );

--
-- INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME, PASSPORT_ID)
-- VALUES('124', 'Rohan','301' );



