

INSERT INTO COURSE(COURSE_ID, COURSE_NAME)
VALUES('101', 'SPRING');

INSERT INTO COURSE(COURSE_ID, COURSE_NAME)
VALUES('102', 'REACT');

INSERT INTO COURSE(COURSE_ID, COURSE_NAME)
VALUES('103', 'ALGO');




INSERT INTO REVIEW(REVIEW_ID, RATING, DESCRIPTION, COURSE_COURSE_ID)
VALUES('201', '4', 'EXCELLENT', '101');

INSERT INTO REVIEW(REVIEW_ID, RATING, DESCRIPTION, COURSE_COURSE_ID)
VALUES('202', '4', 'Awesome', '103');


INSERT INTO REVIEW(REVIEW_ID, RATING, DESCRIPTION, COURSE_COURSE_ID)
VALUES('203', '4', 'Nice', '103');
